Repository 100-hours-a-week/5-bigbrother-slimdealz-fe, pull requests merged in 2024-08, with the labels that each got.

#1 Feat: 페이지 초기 세팅 및 router설정
  src/Router.tsx
  src/index.tsx
  src/pages/category/index.tsx
  src/pages/category/styles.tsx
  src/pages/detail/index.tsx
  src/pages/detail/styles.tsx
  src/pages/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles.tsx
  src/pages/search/initial/index.tsx
  src/pages/search/initial/styles.tsx
  src/pages/search/results/index.tsx
  src/pages/search/results/styles.tsx
  src/pages/signIn/index.tsx
  src/pages/signIn/styles.tsx
  src/pages/signUp/index.tsx
  src/pages/signUp/styles.tsx
  src/pages/user/alarm/index.tsx
  src/pages/user/alarm/styles.tsx
  src/pages/user/bookmark/index.tsx
  src/pages/user/bookmark/styles.tsx
  src/pages/user/information/index.tsx
  src/pages/user/information/styles.tsx
  src/pages/user/recentlyView/index.tsx
  src/pages/user/recentlyView/styles.tsx
Labels: Feat

#32 feat: ProductSlider 컴포넌트 생성
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/Router.tsx
  src/components/product/productSlider/index.tsx
  src/components/product/productSlider/styles.tsx
  src/components/utils/arrow/index.tsx
  src/components/utils/arrow/styles.tsx
  src/components/utils/block/index.tsx
  src/components/utils/block/styles.tsx
  src/pages/detail/index.tsx
  src/pages/main/index.tsx
  src/styles/globalStyles.tsx
  yarn.lock
Labels: Feat

#33 feat: IconCategory 컴포넌트 생성
  index.html
  public/assets/chickenChest.png
  public/assets/slimdealzlogo.png
  public/assets/slimdealzlogo2.png
  src/components/icon/iconCategory/index.tsx
  src/components/icon/iconCategory/styles.tsx
  src/components/product/productSlider/styles.tsx
  src/pages/category/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles.tsx
  src/styles/globalStyles.tsx
Labels: Feat

#34 feat: categoryList 컴포넌트
  package.json
  src/components/list/categoryList/index.tsx
  src/components/list/categoryList/styles.tsx
  src/pages/category/index.tsx
  src/pages/category/styles.tsx
  src/pages/detail/styles.tsx
  yarn.lock
Labels: Feat

#42 푸터 mui 네비게이션
  src/components/layoutWrapper/footer/index.tsx
  src/components/layoutWrapper/footer/styles.tsx
  src/components/layoutWrapper/header/SearchBar.tsx
  src/components/layoutWrapper/header/index.tsx
  src/components/layoutWrapper/header/styles.tsx
Labels: Design, Feat

#43 Feat: 디테일스크린 하단 컴포넌트
  package.json
  src/Router.tsx
  src/components/chart/index.tsx
  src/components/chart/styles.tsx
  src/components/list/mallList/index.tsx
  src/components/list/mallList/styles.tsx
  src/components/list/reviewList/index.tsx
  src/components/list/reviewList/styles.tsx
  src/components/priceAlertModal/index.tsx
  src/components/priceAlertModal/styles.tsx
  src/components/priceAlertSetting/index.tsx
  src/components/priceAlertSetting/styles.tsx
  src/components/tab/index.tsx
  src/components/tab/styles.tsx
  src/pages/detail/index.tsx
  src/pages/detail/styles.tsx
  yarn.lock
Labels: Feat

#44 feat: 추가수정
  src/components/layoutWrapper/header/index.tsx
  src/components/list/mallList/index.tsx
  src/components/priceAlertSetting/index.tsx
Labels: Feat

#45 feat: dev 버전 업데이트를 위한 marge
  package.json
  src/components/icon/iconCategory/index.tsx
  src/components/icon/iconCategory/styles.tsx
  src/components/list/categoryList/index.tsx
  src/components/list/categoryList/styles.tsx
  src/components/product/productSlider/styles.tsx
  src/components/tag/pageNameTag/styles.tsx
  src/pages/category/index.tsx
  src/pages/main/styles.tsx
  yarn.lock
Labels: Feat

#48 refactor: Outlet적용
  src/components/layoutWrapper/footer/index.tsx
  src/components/layoutWrapper/footer/styles.tsx
  src/components/layoutWrapper/header/index.tsx
  src/components/layoutWrapper/header/styles.tsx
  src/pages/detail/index.tsx
  src/pages/index.tsx
Labels: Refactor

#46 최근 검색어, 자동 완성, 인기 검색어 구현
  README.md
  src/components/layoutWrapper/header/SearchBar.tsx
  src/components/searches/popularSearches/index.tsx
  src/components/searches/popularSearches/styles.tsx
  src/components/searches/recentSearches/index.tsx
  src/components/searches/recentSearches/styles.tsx
  src/components/searches/recommendSearches/index.tsx
  src/components/searches/recommendSearches/styles.tsx
  src/components/searches/searchUtils/searchName.tsx
  src/components/searches/searchUtils/searchWord.tsx
Labels: Feat

#49 feat: header와 footer 위치 수정 및 기능 수정
  .babelrc
  Dockerfile
  babel.config.js
  dist/assets/index-B8nx6A8z.css
  dist/assets/index-xIz1-Lit.js
  dist/assets/slimdealzlogo-USQGELi8.png
  dist/favicon.ico
  dist/index.html
  dist/logo192.png
  dist/logo512.png
  dist/manifest.json
  dist/robots.txt
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/box/styles.tsx
  src/components/layoutWrapper/footer/index.tsx
  src/components/layoutWrapper/footer/styles.tsx
  src/components/layoutWrapper/header/SearchBar.tsx
  src/components/layoutWrapper/header/index.tsx
  src/components/layoutWrapper/header/styles.tsx
  src/components/product/productInfo/infoUtils/productRating.tsx
  src/components/product/productInfo/infoUtils/productUrl.tsx
  src/components/product/productSlider/index.tsx
  src/components/searches/recommendSearches/index.tsx
  src/components/tab/index.tsx
  src/components/utils/scrollToTop/scrollToTop.tsx
  src/logo.svg
  src/pages/detail/index.tsx
  src/pages/detail/styles.tsx
  src/pages/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles.tsx
  src/pages/search/initial/index.tsx
  src/pages/search/results/index.tsx
  src/pages/search/results/styles.tsx
  src/pages/user/bookmark/index.tsx
  src/pages/user/bookmark/styles.tsx
  src/pages/user/myMain/index.tsx
  src/pages/user/myMain/styles.tsx
  src/styles/globalStyles.tsx
  yarn.lock
Labels: Feat

#52 feat: header 패딩 동적설정
  src/App.tsx
  src/components/layoutWrapper/header/index.tsx
  src/pages/index.tsx
  src/styles/globalStyles.tsx
Labels: Feat

#67 feat: 북마크 & 로그인 배포 api 연결 처리
  src/components/layoutWrapper/footer/index.tsx
  src/components/list/categoryList/index.tsx
  src/components/product/productInfo/index.tsx
  src/components/product/productInfo/infoUtils/productBookmark.tsx
  src/pages/main/index.tsx
  src/pages/signIn/index.tsx
  src/pages/signIn/styles.tsx
  src/pages/signUp/index.tsx
  src/pages/user/bookmark/index.tsx
  src/pages/user/information/index.tsx
Labels: Feat
